server:
  port: ":9000"
  readTimeOut: 5
  writeTimeOut: 10

database:
  client: "postgres"
  port: 5432
  user: "jump"
  password: "jump@123"
  host: "localhost"
  db: "express"

EXAMPLE_VAR: "variable from config.yml"
EXAMPLE_PATH: "path from config.yml"
